// BabyQ — schedule data transcribed from docs/imunisasi/jadwal-vaksin.jpg
// (Jadwal Imunisasi Anak 2024, Umur 0–18 tahun — rekomendasi Satgas Imunisasi PP IDAI)
// and explanations from docs/imunisasi/penjelasan-vaksin.jpg (Kemenkes).

const AGE_COLUMNS = [
  { months: 0,   label: { id: 'Lahir',  en: 'Birth' } },
  { months: 1,   label: { id: '1 bln',  en: '1 mo'  } },
  { months: 2,   label: { id: '2 bln',  en: '2 mo'  } },
  { months: 3,   label: { id: '3 bln',  en: '3 mo'  } },
  { months: 4,   label: { id: '4 bln',  en: '4 mo'  } },
  { months: 6,   label: { id: '6 bln',  en: '6 mo'  } },
  { months: 9,   label: { id: '9 bln',  en: '9 mo'  } },
  { months: 12,  label: { id: '12 bln', en: '12 mo' } },
  { months: 18,  label: { id: '18 bln', en: '18 mo' } },
  { months: 24,  label: { id: '2 th',   en: '2 yr'  } },
  { months: 36,  label: { id: '3 th',   en: '3 yr'  } },
  { months: 48,  label: { id: '4 th',   en: '4 yr'  } },
  { months: 60,  label: { id: '5 th',   en: '5 yr'  } },
  { months: 72,  label: { id: '6 th',   en: '6 yr'  } },
  { months: 84,  label: { id: '7 th',   en: '7 yr'  } },
  { months: 96,  label: { id: '8 th',   en: '8 yr'  } },
  { months: 108, label: { id: '9 th',   en: '9 yr'  } },
  { months: 120, label: { id: '10 th',  en: '10 yr' } },
  { months: 132, label: { id: '11 th',  en: '11 yr' } },
  { months: 144, label: { id: '12 th',  en: '12 yr' } },
  { months: 156, label: { id: '13 th',  en: '13 yr' } },
  { months: 168, label: { id: '14 th',  en: '14 yr' } },
  { months: 180, label: { id: '15 th',  en: '15 yr' } },
  { months: 192, label: { id: '16 th',  en: '16 yr' } },
  { months: 204, label: { id: '17 th',  en: '17 yr' } },
  { months: 216, label: { id: '18 th',  en: '18 yr' } },
];

// Every age column at/after `startMonths` becomes a clickable repeat instance.
function yearlyDoses(startMonths, step) {
  return AGE_COLUMNS
    .filter(c => c.months >= startMonths && (c.months - startMonths) % step === 0)
    .map(c => ({ code: '→', months: c.months, repeat: true }));
}

const VACCINES = [
  {
    id: 'hepb', color: '#F3D3E0',
    name: { id: 'Hepatitis B', en: 'Hepatitis B' },
    prevents: {
      id: 'Mencegah penyakit hepatitis B yang dapat menyebabkan kerusakan hati dan kanker.',
      en: 'Prevents hepatitis B disease, which can cause liver damage and cancer.',
    },
    doses: [{ code: 'HB-0', months: 0 }],
  },
  {
    id: 'bcg', color: '#D2EAD9',
    name: { id: 'BCG', en: 'BCG' },
    prevents: {
      id: 'Mencegah TBC (tuberkulosis) paru dan komplikasi serius seperti TBC tulang dan radang otak.',
      en: 'Prevents pulmonary TB (tuberculosis) and serious complications such as bone TB and meningitis.',
    },
    doses: [{ code: 'BCG', months: 1 }],
  },
  {
    id: 'polio', color: '#F6D8CE',
    name: { id: 'Polio', en: 'Polio' },
    prevents: {
      id: 'Mencegah polio, virus yang menyerang otak dan sumsum tulang belakang yang dapat menyebabkan kelumpuhan pada kaki.',
      en: 'Prevents polio, a virus that attacks the brain and spinal cord and can cause leg paralysis.',
    },
    doses: [
      { code: 'OPV 1', months: 2 },
      { code: 'OPV 2', months: 3 },
      { code: 'OPV 3', months: 4 },
      { code: 'OPV 4 / IPV', months: 6 },
    ],
  },
  {
    id: 'dpt', color: '#F8E2C9',
    name: { id: 'DPT', en: 'DPT' },
    prevents: {
      id: 'Mencegah difteri (infeksi hidung dan tenggorokan yang menyebabkan kesulitan bernapas), pertusis (batuk rejan), dan tetanus (kejang otot rahang dan leher).',
      en: 'Prevents diphtheria (nose and throat infection causing breathing difficulty), pertussis (whooping cough), and tetanus (jaw and neck muscle spasms).',
    },
    doses: [
      { code: 'DPT 1', months: 2 },
      { code: 'DPT 2', months: 3 },
      { code: 'DPT 3', months: 4 },
    ],
  },
  {
    id: 'campak', color: '#EBDAEE',
    name: { id: 'Campak', en: 'Measles' },
    prevents: {
      id: 'Mencegah penyakit campak (demam, ruam merah) dan rubela atau campak jerman, dapat menyebabkan infeksi telinga, pneumonia, kejang, kerusakan otak dan kematian.',
      en: 'Prevents measles (fever, red rash) and rubella (German measles), which can cause ear infection, pneumonia, seizures, brain damage, and death.',
    },
    doses: [
      { code: 'Campak 1 / MR', months: 9 },
      { code: 'Campak 2', months: 18 },
      { code: 'Campak 3 / MR', months: 72 },
    ],
  },
  {
    id: 'hib', color: '#F7EBC9',
    name: { id: 'Hib', en: 'Hib' },
    prevents: {
      id: 'Mencegah penyakit akibat kuman Hib seperti radang otak (meningitis), infeksi darah (sepsis), radang paru (pneumonia), radang katup napas (epiglotitis).',
      en: 'Prevents diseases caused by Hib bacteria such as meningitis, blood infection (sepsis), pneumonia, and epiglottitis.',
    },
    doses: [
      { code: 'Hib 1', months: 2 },
      { code: 'Hib 2', months: 3 },
      { code: 'Hib 3', months: 4 },
    ],
  },
  {
    id: 'pcv', color: '#F3D3E0',
    name: { id: 'PCV', en: 'PCV' },
    prevents: {
      id: 'Mencegah penyakit akibat infeksi kuman Pneumokokus, seperti pneumonia, meningitis dan infeksi darah (sepsis).',
      en: 'Prevents diseases caused by pneumococcal infection, such as pneumonia, meningitis, and blood infection (sepsis).',
    },
    doses: [
      { code: 'PCV 1', months: 2 },
      { code: 'PCV 2', months: 3 },
      { code: 'PCV 3', months: 12 },
    ],
  },
  {
    id: 'rotavirus', color: '#D2EAD9',
    name: { id: 'Rotavirus', en: 'Rotavirus' },
    prevents: {
      id: 'Mencegah diare akut (muntah dan buang air besar encer yang hebat).',
      en: 'Prevents acute diarrhea (severe vomiting and watery stools).',
    },
    doses: [
      { code: 'RV 1', months: 2 },
      { code: 'RV 2', months: 3 },
      { code: 'RV 3', months: 4 },
    ],
  },
  {
    id: 'influenza', color: '#F6D8CE',
    name: { id: 'Influenza', en: 'Influenza' },
    prevents: {
      id: 'Mencegah infeksi virus Influenza (demam, batuk, pilek disertai nyeri otot). Diulang setiap tahun.',
      en: 'Prevents influenza virus infection (fever, cough, runny nose with muscle aches). Repeated every year.',
    },
    doses: [{ code: 'Influenza', months: 6 }, ...yearlyDoses(12, 12)],
  },
  {
    id: 'dengue', color: '#F8E2C9',
    name: { id: 'Dengue (DBV)', en: 'Dengue (DBV)' },
    prevents: {
      id: 'Mencegah demam berdarah dengue (DBD).',
      en: 'Prevents dengue hemorrhagic fever (DHF).',
    },
    doses: [
      { code: 'DBV 1', months: 12 },
      { code: 'DBV 2', months: 18 },
      { code: 'DBV 3', months: 24 },
    ],
  },
  {
    id: 'je', color: '#EBDAEE',
    name: { id: 'Japanese Encephalitis (TBE)', en: 'Japanese Encephalitis (TBE)' },
    prevents: {
      id: 'Mencegah penyakit akibat virus Japanese encephalitis yang ditularkan melalui gigitan nyamuk, dapat menyebabkan radang otak.',
      en: 'Prevents disease caused by the Japanese encephalitis virus, transmitted through mosquito bites, which can cause brain inflammation.',
    },
    doses: [
      { code: 'TBE 1', months: 12 },
      { code: 'TBE 2', months: 18 },
    ],
  },
  {
    id: 'tipoid', color: '#F7EBC9',
    name: { id: 'Tipoid', en: 'Typhoid' },
    prevents: {
      id: 'Mencegah penyakit tifoid atau demam tifoid ("tipes") yang disebabkan infeksi bakteri Salmonella typhi. Diulang setiap 3 tahun.',
      en: 'Prevents typhoid fever caused by Salmonella typhi bacterial infection. Repeated every 3 years.',
    },
    doses: [{ code: 'Tipoid 1', months: 36 }, ...yearlyDoses(72, 36)],
  },
  {
    id: 'hepa', color: '#F3D3E0',
    name: { id: 'Hepatitis A', en: 'Hepatitis A' },
    prevents: {
      id: 'Mencegah penyakit hepatitis A (infeksi hati yang sangat menular).',
      en: 'Prevents hepatitis A (a highly contagious liver infection).',
    },
    doses: [
      { code: 'HepA 1', months: 24 },
      { code: 'HepA 2', months: 36 },
    ],
  },
  {
    id: 'varisela', color: '#D2EAD9',
    name: { id: 'Varisela', en: 'Varicella' },
    prevents: {
      id: 'Mencegah penyakit cacar air (demam disertai ruam lepuhan berisi air di seluruh badan yang dapat menimbulkan bekas luka permanen).',
      en: 'Prevents chickenpox (fever with fluid-filled blisters all over the body that can leave permanent scars).',
    },
    doses: [
      { code: 'Varisela 1', months: 36 },
      { code: 'Varisela 2', months: 48 },
    ],
  },
  {
    id: 'mmr', color: '#F6D8CE',
    name: { id: 'MMR', en: 'MMR' },
    prevents: {
      id: 'Mencegah penyakit gondongan (pembengkakan kelenjar ludah di bawah telinga, dapat menyebabkan radang otak, tuli, radang testis/ovarium), campak (measles) dan rubela (campak jerman).',
      en: 'Prevents mumps (swelling of salivary glands below the ears, can cause brain inflammation, deafness, testicular/ovarian inflammation), measles, and rubella (German measles).',
    },
    doses: [
      { code: 'MMR 1', months: 12 },
      { code: 'MMR 2', months: 72 },
    ],
  },
  {
    id: 'td', color: '#F8E2C9',
    name: { id: 'Td', en: 'Td' },
    prevents: {
      id: 'Vaksin Td (Tetanus difteria) untuk melengkapi dosis vaksin DPT sebelumnya.',
      en: 'Td vaccine (Tetanus diphtheria) to complete the previous DPT vaccine doses.',
    },
    doses: [
      { code: 'Td 1', months: 84 },
      { code: 'Td 2', months: 96 },
      { code: 'Td 3', months: 108 },
    ],
  },
  {
    id: 'hpv', color: '#EBDAEE',
    name: { id: 'HPV', en: 'HPV' },
    prevents: {
      id: 'Mencegah kanker serviks pada wanita.',
      en: 'Prevents cervical cancer in women.',
    },
    doses: [
      { code: 'HPV 1', months: 60 },
      { code: 'HPV 2', months: 72 },
    ],
  },
  {
    id: 'covid', color: '#F7EBC9',
    name: { id: 'Covid-19', en: 'Covid-19' },
    prevents: {
      id: 'Mencegah infeksi virus Covid-19.',
      en: 'Prevents Covid-19 virus infection.',
    },
    doses: [
      { code: 'Covid-19', months: 72 },
      { code: '→', months: 84, repeat: true },
    ],
  },
];

const I18N = {
  id: {
    tagline: 'Jadwal & catatan imunisasi anak',
    login: 'Masuk',
    signup: 'Daftar',
    email: 'Email',
    password: 'Kata sandi',
    fullName: 'Nama lengkap',
    continueGoogle: 'Lanjutkan dengan Google',
    or: 'atau',
    noAccount: 'Belum punya akun? Daftar',
    haveAccount: 'Sudah punya akun? Masuk',
    authError: 'Email atau kata sandi salah.',
    emailUsed: 'Email sudah terdaftar. Silakan masuk.',
    logout: 'Keluar',
    children: 'Anak',
    addChild: 'Tambah anak',
    editChild: 'Ubah data anak',
    childName: 'Nama anak',
    dob: 'Tanggal lahir',
    sex: 'Jenis kelamin (opsional)',
    male: 'Laki-laki',
    female: 'Perempuan',
    save: 'Simpan',
    cancel: 'Batal',
    delete: 'Hapus',
    confirmDeleteChild: 'Hapus data anak beserta seluruh catatan imunisasinya?',
    confirmDeleteRecord: 'Hapus catatan vaksin ini?',
    welcomeTitle: 'Selamat datang di BabyQ!',
    welcomeText: 'Mulai dengan menambahkan data anak Anda untuk melihat jadwal imunisasinya.',
    sampleData: 'Muat data contoh',
    ageNow: 'Umur',
    monthsUnit: 'bulan',
    yearsUnit: 'tahun',
    progressDone: 'dosis selesai',
    scheduleTitle: 'Jadwal Imunisasi Anak 2024',
    scheduleSubtitle: 'Umur 0–18 tahun',
    vaccineCol: 'Vaksin',
    ageCol: 'Umur',
    footerNote: 'Jadwal imunisasi sesuai rekomendasi Satgas Imunisasi PP IDAI (Ikatan Dokter Anak Indonesia).',
    statusDone: 'Selesai',
    statusDue: 'Jatuh tempo',
    statusOverdue: 'Terlambat',
    statusUpcoming: 'Akan datang',
    notifications: 'Notifikasi',
    noNotifications: 'Tidak ada notifikasi. Semua jadwal terkendali!',
    notifOverdue: 'sudah terlambat',
    notifDue: 'jatuh tempo sekarang',
    notifUpcoming: 'akan jatuh tempo',
    notifFor: 'untuk',
    scheduledAt: 'Jadwal',
    status: 'Status',
    givenOn: 'Tanggal pemberian',
    brand: 'Merk/tipe vaksin',
    brandPlaceholder: 'cth. Engerix-B, Pentabio, dsb.',
    note: 'Catatan',
    notePlaceholder: 'cth. diberikan di Puskesmas, anak demam ringan setelahnya',
    markDone: 'Simpan catatan',
    updateRecord: 'Perbarui catatan',
    deleteRecord: 'Hapus catatan',
    recordedOn: 'Diberikan pada',
    explanation: 'Penjelasan vaksin',
    repeatYearly: 'Dosis rutin (diulang sesuai jadwal)',
    langLabel: 'EN',
    clickCellHint: 'Klik sel untuk mencatat pemberian vaksin',
    prevCols: 'Sebelumnya',
    nextCols: 'Berikutnya',
    backToNow: 'Kembali ke umur sekarang',
  },
  en: {
    tagline: 'Child immunization schedule & records',
    login: 'Log in',
    signup: 'Sign up',
    email: 'Email',
    password: 'Password',
    fullName: 'Full name',
    continueGoogle: 'Continue with Google',
    or: 'or',
    noAccount: "Don't have an account? Sign up",
    haveAccount: 'Already have an account? Log in',
    authError: 'Incorrect email or password.',
    emailUsed: 'Email already registered. Please log in.',
    logout: 'Log out',
    children: 'Children',
    addChild: 'Add child',
    editChild: 'Edit child',
    childName: 'Child name',
    dob: 'Date of birth',
    sex: 'Sex (optional)',
    male: 'Male',
    female: 'Female',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirmDeleteChild: 'Delete this child and all their immunization records?',
    confirmDeleteRecord: 'Delete this vaccine record?',
    welcomeTitle: 'Welcome to BabyQ!',
    welcomeText: "Start by adding your child's data to see their immunization schedule.",
    sampleData: 'Load sample data',
    ageNow: 'Age',
    monthsUnit: 'months',
    yearsUnit: 'years',
    progressDone: 'doses done',
    scheduleTitle: 'Childhood Immunization Schedule 2024',
    scheduleSubtitle: 'Age 0–18 years',
    vaccineCol: 'Vaccine',
    ageCol: 'Age',
    footerNote: 'Schedule follows the recommendation of the IDAI (Indonesian Pediatric Society) Immunization Task Force.',
    statusDone: 'Done',
    statusDue: 'Due now',
    statusOverdue: 'Overdue',
    statusUpcoming: 'Upcoming',
    notifications: 'Notifications',
    noNotifications: 'No notifications. Everything is on track!',
    notifOverdue: 'is overdue',
    notifDue: 'is due now',
    notifUpcoming: 'is coming up',
    notifFor: 'for',
    scheduledAt: 'Scheduled',
    status: 'Status',
    givenOn: 'Date given',
    brand: 'Vaccine brand/type',
    brandPlaceholder: 'e.g. Engerix-B, Pentabio, etc.',
    note: 'Note',
    notePlaceholder: 'e.g. given at community clinic, mild fever afterwards',
    markDone: 'Save record',
    updateRecord: 'Update record',
    deleteRecord: 'Delete record',
    recordedOn: 'Given on',
    explanation: 'About this vaccine',
    repeatYearly: 'Routine dose (repeated per schedule)',
    langLabel: 'ID',
    clickCellHint: 'Click a cell to record a vaccination',
    prevCols: 'Previous',
    nextCols: 'Next',
    backToNow: 'Back to current age',
  },
};
